-- ============================================================================
-- Red Box Motors — Sales & Consignment form system (2026-07-07)
-- Run in the Supabase SQL editor against the live project. Safe to re-run.
--
-- Ships together with app changes: /dealer/sell multi-step consignment form,
-- vehicle-specific inquiry form, First Look form, contact-form rework, and
-- the /api/consignments route. Until this patch is applied the new forms
-- degrade gracefully: submissions land in public.leads as type 'contact'
-- with all structured detail formatted into `message` (nothing is lost);
-- once applied, the API automatically switches to the structured shape.
--
-- Design: all form types share public.leads. Form-specific structured fields
-- live in `payload` (jsonb) — one hardened pipeline, one admin surface.
-- Uploaded files live in a PRIVATE storage bucket keyed by lead id
-- (lead-uploads/leads/<lead_id>/<category>/...); storage is the source of
-- truth for files, so no join table is needed.
-- ============================================================================

-- 1) New lead types. (Values are only added here, never used in this script,
--    so this is transaction-safe on PG 12+.)
alter type lead_type add value if not exists 'consignment';
alter type lead_type add value if not exists 'first_look';

-- 2) Shared structured columns on leads.
alter table public.leads add column if not exists contact_method text;
alter table public.leads add column if not exists city_state     text;
alter table public.leads add column if not exists payload        jsonb;
alter table public.leads add column if not exists submission_key text;

-- Idempotency: the client generates one key per submission attempt; rapid
-- double-submits collapse into one row (the API treats a conflict as success).
create unique index if not exists leads_submission_key_idx
  on public.leads (submission_key) where submission_key is not null;

-- 3) Private uploads bucket. NOT public; no storage.objects policies on
--    purpose — with RLS enabled and zero policies, anon/authenticated can
--    neither read, list, nor write. All access is service-role mediated:
--    * uploads: short-lived signed upload URLs issued by /api/consignments
--      AFTER honeypot / rate-limit / validation / Turnstile gates,
--    * admin reads: signed download URLs generated by an admin-only server
--      action (requireUser allowlist) in /admin/leads.
--    Type + size are enforced server-side by the bucket itself
--    (allowed_mime_types / file_size_limit) even for direct uploads.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'lead-uploads', 'lead-uploads', false,
  10485760, -- 10 MB per file (stated in the form UI)
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif',
        'image/heic', 'image/heif', 'application/pdf']
)
on conflict (id) do update
  set public = false,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- 4) PostgREST caches the schema — reload so the API sees the new columns
--    and enum values immediately.
notify pgrst, 'reload schema';
